create table if not exists memories(id text primary key,user_id text,segment integer default 0,content text not null,simhash text,primary_sector text not null,tags text,meta text,created_at integer,updated_at integer,last_seen_at integer,salience real,decay_lambda real,version integer default 1,mean_dim integer,mean_vec BYTEA,compressed_vec BYTEA,feedback_score real default 0);
create table if not exists vectors(id text not null,sector text not null,user_id text,v BYTEA not null,dim integer not null,primary key(id,sector));
create table if not exists waypoints(src_id text,dst_id text not null,user_id text,weight real not null,created_at integer,updated_at integer,primary key(src_id,user_id));
create table if not exists embed_logs(id text primary key,model text,status text,ts integer,err text);
create table if not exists users(user_id text primary key,summary text,reflection_count integer default 0,created_at integer,updated_at integer);
create table if not exists stats(id SERIAL primary key,type text not null,count integer default 1,ts bigint not null);
create table if not exists temporal_facts(id text primary key,subject text not null,predicate text not null,object text not null,valid_from integer not null,valid_to integer,confidence real not null check(confidence >= 0 and confidence <= 1),last_updated integer not null,metadata text,unique(subject,predicate,object,valid_from));
create table if not exists temporal_edges(id text primary key,source_id text not null,target_id text not null,relation_type text not null,valid_from integer not null,valid_to integer,weight real not null,metadata text,foreign key(source_id) references temporal_facts(id),foreign key(target_id) references temporal_facts(id));
create index if not exists idx_memories_sector on memories(primary_sector);
create index if not exists idx_memories_segment on memories(segment);
create index if not exists idx_memories_simhash on memories(simhash);
create index if not exists idx_memories_ts on memories(last_seen_at);
create index if not exists idx_memories_user on memories(user_id);
create index if not exists idx_vectors_user on vectors(user_id);
create index if not exists idx_waypoints_src on waypoints(src_id);
create index if not exists idx_waypoints_dst on waypoints(dst_id);
create index if not exists idx_waypoints_user on waypoints(user_id);
create index if not exists idx_stats_ts on stats(ts);
create index if not exists idx_stats_type on stats(type);
create index if not exists idx_temporal_subject on temporal_facts(subject);
create index if not exists idx_temporal_predicate on temporal_facts(predicate);
create index if not exists idx_temporal_validity on temporal_facts(valid_from,valid_to);
create index if not exists idx_temporal_composite on temporal_facts(subject,predicate,valid_from,valid_to);
create index if not exists idx_edges_source on temporal_edges(source_id);
create index if not exists idx_edges_target on temporal_edges(target_id);
create index if not exists idx_edges_validity on temporal_edges(valid_from,valid_to);
